#!/usr/local/bin/python3

import subprocess, sys, os, re, argparse
from logging import getLogger
from os.path import isfile, isdir, abspath, normpath, dirname, join, basename

def main():
    log = getLogger(basename(__file__))
    files = sys.argv[1:]

    regexs = {
        "AWS Key": "[a-z0-9\/+]{40}",
        "Possible Key": "[\"\'\`][0-9a-zA-Z_]{20,}[\"\'\`]",
        "Possible Password": "(pass(word)? ?= ?[\"\'\`].*?[\"\'\`])"
    }

    for file in files:
        with open(file, 'rb') as f:
            content = str(f.read())
            for regex in regexs:
                pattern =  regexs[regex]
                if re.search(pattern,content) is not None:
                    print ("Found "+regex+" in "+file+":  "+re.search(pattern,content).group(0))
                    sys.exit(1)

    return 0

if __name__ == '__main__':
    main()
